import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import{getFirestore,addDoc,collection,doc,getDocs,orderBy,query,serverTimestamp,updateDoc}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const cfg={apiKey:'AIzaSyAHKlqvpQ_DTY3rnILOeOQeKgI8LKOhk0w',authDomain:'nh-mmi-recruitment.firebaseapp.com',projectId:'nh-mmi-recruitment',storageBucket:'nh-mmi-recruitment.firebasestorage.app',messagingSenderId:'142761644358',appId:'1:142761644358:web:f742076fc108b74c411547'};
const fire=initializeApp(cfg),auth=getAuth(fire),db=getFirestore(fire),root=document.getElementById('app');
const branches={
'Medical (Doctors & Consultants)':['RMO','Senior Medical Officer','Senior Resident','Junior Consultant','Associate Consultant','Consultant','Senior Consultant','Other'],
'Nursing':['Staff Nurse','Senior Nurse','Incharge','ICU/OT Cath Nurse','Other'],
'Technicians & Diagnostics':['Lab Technician','Radiology/X-Ray Tech','OT Technician','ECG/Echo Tech','Dialysis Tech','Cath Lab Tech','Other'],
'Paramedical & Allied Health':['Physiotherapist','Dietitian','Pharmacist','Other'],
'Administrative & Management':['HR Executive','Finance/Accounts','Marketing','Front Office/Reception','Store/Purchase','IT','Administrator/Manager','Billing Executive','Other'],
'Support & Facility Services':['Housekeeping','Security Guard','CSSD Attendant','Patient Attendant/Ward Boy','Driver','Kitchen/Dietary Staff','Other'],
'Other':['Other']};
const exps=['0 Year','0 - 1 Year','1 - 3 Years','3 - 6 Years','6 - 10 Years','10+ Years'];
const statuses=['New','Shortlisted','Called','Interview Scheduled','Interviewed','Selected','Rejected','On Hold'];
let cv=null,rows=[],filters={q:'',dept:'',status:''};
const isAdminPage=location.pathname.toLowerCase().includes('admin');
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const opt=a=>a.map(x=>`<option>${esc(x)}</option>`).join('');
const date=v=>{try{return v?.toDate?v.toDate().toLocaleString():'-'}catch{return'-'}};
function shell(title,sub,mode,body){root.innerHTML=`<main class="page ${mode}"><section class="hero"><div class="heroShade"></div><div class="brand"><div class="mark">NH</div><div><p class="pill">MMI Narayana Health Raipur</p><h1>${title}</h1><p>${sub}</p></div></div></section>${body}</main>`}
function statusBox(type,title,text){let el=document.getElementById('statusBox');if(!el)return;el.className='statusBox '+type;el.innerHTML=`<div class="statusIcon">${type==='green'?'✓':type==='yellow'?'↻':'!'}</div><div><b>${title}</b><p>${text}</p></div>`;el.hidden=false}
function party(){let c=document.createElement('div');c.className='confetti';c.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><b>Application Submitted</b>';document.body.appendChild(c);setTimeout(()=>c.remove(),3200)}
function compress(file){return new Promise((res,rej)=>{if(!file)return rej(Error('Please select a CV image.'));if(!['image/jpeg','image/jpg','image/png'].includes(file.type))return rej(Error('Only JPG/PNG CV images are allowed.'));let img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{let w=img.width,h=img.height,max=1400;if(w>max||h>max){let s=Math.min(max/w,max/h);w=Math.round(w*s);h=Math.round(h*s)}let c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);let q=.78,out=c.toDataURL('image/jpeg',q);while(out.length>620000&&q>.35){q-=.08;out=c.toDataURL('image/jpeg',q)}if(out.length>900000)return rej(Error('Image is too large. Please upload a clearer compressed screenshot/photo.'));res({data:out,name:file.name.replace(/\.[^/.]+$/,'.jpg'),type:'image/jpeg',size:Math.round(out.length*.75)})};img.onerror=()=>rej(Error('Could not read image.'));img.src=r.result};r.onerror=()=>rej(Error('Could not read file.'));r.readAsDataURL(file)})}
function candidate(){shell('Recruitment Application','Submit your details and upload a clear JPG/PNG image of your CV for HR review.','candidate',`<form class="card formCard" id="form"><div class="statusBox" id="statusBox" hidden></div><div class="grid"><div><label>Name *</label><input name="name" required minlength="2" maxlength="80" placeholder="Full name"></div><div><label>WhatsApp / Phone *</label><input name="phone" required minlength="10" maxlength="15" placeholder="10 digit mobile number"></div><div class="full"><label>About Me</label><textarea name="aboutMe" maxlength="1000" placeholder="Briefly mention your skills, current role, department preference, or experience"></textarea></div><div><label>Department *</label><select name="department" required><option value="">Select Department</option>${opt(Object.keys(branches))}</select></div><div><label>Role *</label><select name="specificRole" required><option value="">Select Role</option></select></div><div class="full" id="customWrap" hidden><label>Write Role</label><input name="customRole" maxlength="80" placeholder="Mention role"></div><div><label>Work Experience *</label><select name="workExperience" required><option value="">Select Experience</option>${opt(exps)}</select></div><div><label>Upload CV Image *</label><input type="file" id="file" accept="image/png,image/jpeg" required></div><div class="full" id="preview"></div></div><div class="submitRow"><button id="submitBtn">Submit Application</button></div></form>`);
let f=document.getElementById('form'),role=f.specificRole;f.department.onchange=()=>{role.innerHTML='<option value="">Select Role</option>'+opt(branches[f.department.value]||[]);toggleCustom()};role.onchange=toggleCustom;function toggleCustom(){document.getElementById('customWrap').hidden=!(role.value==='Other'||f.department.value==='Other')}
document.getElementById('file').onchange=async e=>{try{cv=null;document.getElementById('preview').innerHTML='';statusBox('yellow','Compressing CV image','Please wait. Your CV image is being optimized for fast upload.');cv=await compress(e.target.files[0]);document.getElementById('preview').innerHTML=`<div class="preview"><img src="${cv.data}"><div><b>${esc(cv.name)}</b><p>Compressed and ready for submission.</p></div></div>`;statusBox('green','CV image ready','Your CV image has been compressed successfully.')}catch(er){statusBox('red','Upload issue',er.message)}};
f.onsubmit=async e=>{e.preventDefault();let btn=document.getElementById('submitBtn');try{if(!cv)throw Error('Please upload CV image.');btn.disabled=true;statusBox('yellow','Submitting application','Your details and CV image are being securely submitted.');let data=Object.fromEntries(new FormData(f).entries());await addDoc(collection(db,'applications'),{...data,cvImageData:cv.data,cvImageName:cv.name,cvImageType:cv.type,cvImageSize:cv.size,applicationStatus:'New',hrRemarks:'',submittedAt:serverTimestamp(),updatedAt:serverTimestamp()});root.innerHTML=`<main class="page success"><section class="doneCard"><div class="doneIcon">✓</div><h1>CV Submitted Successfully</h1><p>Your application has been received by MMI Narayana Health Raipur HR.</p><button onclick="location.reload()">Submit Another Application</button></section></main>`;party()}catch(er){btn.disabled=false;statusBox('red','Submission failed',er.message||'Please try again.')}}}
function login(){shell('HR Admin Login','Authorized HR users can review applications, update remarks, and export candidate data.','admin',`<form class="card loginCard" id="login"><div class="statusBox red" id="statusBox" hidden></div><label>Email</label><input name="email" type="email" required placeholder="HR email"><label>Password</label><input name="password" type="password" required placeholder="Password"><button>Login to Dashboard</button></form>`);document.getElementById('login').onsubmit=async e=>{e.preventDefault();let f=e.target;try{await signInWithEmailAndPassword(auth,f.email.value,f.password.value)}catch(er){statusBox('red','Login failed',er.message)}}}
async function load(){let snap=await getDocs(query(collection(db,'applications'),orderBy('submittedAt','desc')));rows=snap.docs.map(d=>({id:d.id,...d.data()}));renderDash()}
function filtered(){return rows.filter(r=>[r.name,r.phone,r.department,r.specificRole,r.customRole,r.aboutMe].join(' ').toLowerCase().includes(filters.q)&&(!filters.dept||r.department===filters.dept)&&(!filters.status||r.applicationStatus===filters.status))}
function renderDash(){shell('HR Dashboard','Search, filter, review About Me, view CV images, update status and remarks.','admin',`<section class="card"><div class="topbar"><h2 id="count">Applications</h2><div class="actions"><button id="csv">Export CSV</button><button class="danger" id="out">Logout</button></div></div><div class="filters"><input id="q" placeholder="Search name, phone, role, about me"><select id="sd"><option value="">All Departments</option>${opt(Object.keys(branches))}</select><select id="ss"><option value="">All Status</option>${opt(statuses)}</select><button id="refresh">Refresh</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Date</th><th>Candidate</th><th>Dept / Role</th><th>About Me</th><th>CV</th><th>Status</th><th>Remarks</th><th>Save</th></tr></thead><tbody id="tbody"></tbody></table></div></section>`);
const q=document.getElementById('q'),sd=document.getElementById('sd'),ss=document.getElementById('ss');q.value=filters.q;sd.value=filters.dept;ss.value=filters.status;q.oninput=()=>{filters.q=q.value.toLowerCase();renderRows()};sd.onchange=()=>{filters.dept=sd.value;renderRows()};ss.onchange=()=>{filters.status=ss.value;renderRows()};document.getElementById('refresh').onclick=load;document.getElementById('out').onclick=()=>signOut(auth);document.getElementById('csv').onclick=()=>exportCSV(filtered());renderRows()}
function renderRows(){let list=filtered();document.getElementById('count').textContent=`Applications (${list.length})`;document.getElementById('tbody').innerHTML=list.map(r=>`<tr><td>${date(r.submittedAt)}</td><td><b>${esc(r.name)}</b><br>${esc(r.phone)}</td><td>${esc(r.department)}<br><b>${esc(r.specificRole==='Other'?r.customRole:r.specificRole)}</b><br>${esc(r.workExperience)}</td><td class="aboutCell">${esc(r.aboutMe||'-')}</td><td>${r.cvImageData?`<img class="thumb" data-view="${r.id}" src="${r.cvImageData}"><br><button class="secondary small" data-view="${r.id}">View</button>`:''}</td><td><select data-st="${r.id}">${statuses.map(s=>`<option ${s===(r.applicationStatus||'New')?'selected':''}>${s}</option>`).join('')}</select></td><td><textarea data-rm="${r.id}">${esc(r.hrRemarks||'')}</textarea></td><td><button class="small" data-save="${r.id}">Save</button></td></tr>`).join('');document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{let id=b.dataset.save;await updateDoc(doc(db,'applications',id),{applicationStatus:document.querySelector(`[data-st="${id}"]`).value,hrRemarks:document.querySelector(`[data-rm="${id}"]`).value,updatedAt:serverTimestamp()});await load()});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(rows.find(x=>x.id===b.dataset.view)))}
function show(r){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modalbox"><div class="topbar"><h2>${esc(r.name)} - CV</h2><button class="secondary">Close</button></div><div class="detail"><b>Phone:</b> ${esc(r.phone)}<br><b>Department:</b> ${esc(r.department)}<br><b>Role:</b> ${esc(r.specificRole==='Other'?r.customRole:r.specificRole)}<br><b>About Me:</b> ${esc(r.aboutMe||'-')}</div><img src="${r.cvImageData}"><br><br><a download="${esc(r.cvImageName||'cv.jpg')}" href="${r.cvImageData}"><button>Download CV Image</button></a></div>`;m.onclick=e=>{if(e.target===m||e.target.textContent==='Close')m.remove()};document.body.appendChild(m)}
function exportCSV(list){let cols=['name','phone','department','specificRole','customRole','workExperience','aboutMe','applicationStatus','hrRemarks','submittedAt'];let s=[cols.join(','),...list.map(r=>cols.map(c=>'"'+String(c==='submittedAt'?date(r[c]):r[c]??'').replaceAll('"','""')+'"').join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='applications.csv';a.click();URL.revokeObjectURL(a.href)}
if(isAdminPage)onAuthStateChanged(auth,u=>u?load():login());else candidate();
