import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import{getFirestore,addDoc,collection,doc,getDocs,orderBy,query,serverTimestamp,updateDoc}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const cfg={apiKey:'AIzaSyAHKlqvpQ_DTY3rnILOeOQeKgI8LKOhk0w',authDomain:'nh-mmi-recruitment.firebaseapp.com',projectId:'nh-mmi-recruitment',storageBucket:'nh-mmi-recruitment.firebasestorage.app',messagingSenderId:'142761644358',appId:'1:142761644358:web:f742076fc108b74c411547'};
const app=initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),root=document.getElementById('app');
const base='/nh-mmi-RECRU_IT/';
const branches={
'Medical (Doctors & Consultants)':['RMO','Senior Medical Officer','Senior Resident','Junior Consultant','Associate Consultant','Consultant','Senior Consultant','Other'],
'Nursing':['Staff Nurse','Senior Nurse','Incharge','ICU/OT Cath Nurse','Other'],
'Technicians & Diagnostics':['Lab Technician','Radiology/X-Ray Tech','OT Technician','ECG/Echo Tech','Dialysis Tech','Cath Lab Tech','Other'],
'Paramedical & Allied Health':['Physiotherapist','Dietitian','Pharmacist','Other'],
'Administrative & Management':['HR Executive','Finance/Accounts','Marketing','Front Office/Reception','Store/Purchase','IT','Administrator/Manager','Billing Executive','Other'],
'Support & Facility Services':['Housekeeping','Security Guard','CSSD Attendant','Patient Attendant/Ward Boy','Driver','Kitchen/Dietary Staff','Other'],
'Other':['Other']};
const exps=['0 Year','0 - 1 Year','1 - 3 Years','3 - 6 Years','6 - 10 Years','10+ Years'];
const statuses=['New','Shortlisted','Called','Interview Scheduled','Interviewed','Selected','Rejected','On Hold'];
let cv=null,rows=[],user=null;
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const opt=a=>a.map(x=>`<option>${esc(x)}</option>`).join('');
const date=v=>{try{return v?.toDate?v.toDate().toLocaleString():'-'}catch{return'-'}};
const header=admin=>`<div class="hero"><div class="brand"><div class="logo">NH</div><div><div class="eyebrow">MMI Narayana Health Raipur</div><h1>${admin?'HR Dashboard':'Recruitment Portal'}</h1><p>${admin?'View applications, update status, remarks and export data.':'Submit your details and upload a clear JPG/PNG image of your CV.'}</p></div></div><br><button class="secondary" id="switch">${admin?'Candidate Form':'HR Admin'}</button></div>`;
function setMsg(t,ok=false){let n=document.getElementById('msg');if(n){n.className='notice '+(ok?'ok':'err');n.textContent=t;n.hidden=false}}
function compress(file){return new Promise((res,rej)=>{if(!['image/jpeg','image/jpg','image/png'].includes(file.type))return rej(Error('Only JPG/PNG CV images are allowed.'));let img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{let w=img.width,h=img.height,max=1400;if(w>max||h>max){let s=Math.min(max/w,max/h);w=Math.round(w*s);h=Math.round(h*s)}let c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);let q=.78,out=c.toDataURL('image/jpeg',q);while(out.length>620000&&q>.35){q-=.08;out=c.toDataURL('image/jpeg',q)}if(out.length>900000)return rej(Error('Image is too large. Please upload a clearer compressed screenshot/photo.'));res({data:out,name:file.name.replace(/\.[^/.]+$/,'.jpg'),type:'image/jpeg',size:Math.round(out.length*.75)})};img.onerror=()=>rej(Error('Could not read image.'));img.src=r.result};r.onerror=()=>rej(Error('Could not read file.'));r.readAsDataURL(file)})}
function candidate(){root.innerHTML=`<main class="wrap">${header(false)}<form class="card" id="form"><div id="msg" hidden></div><div class="grid"><div><label>Name *</label><input name="name" required minlength="2" maxlength="80"></div><div><label>WhatsApp / Phone *</label><input name="phone" required minlength="10" maxlength="15"></div><div class="full"><label>About Me</label><textarea name="aboutMe" maxlength="1000"></textarea></div><div><label>Department *</label><select name="department" required><option value="">Select Department</option>${opt(Object.keys(branches))}</select></div><div><label>Role *</label><select name="specificRole" required><option value="">Select Role</option></select></div><div class="full" id="customWrap" style="display:none"><label>Write Role</label><input name="customRole" maxlength="80"></div><div><label>Work Experience *</label><select name="workExperience" required><option value="">Select Experience</option>${opt(exps)}</select></div><div><label>CV Image JPG/PNG *</label><input type="file" id="file" accept="image/png,image/jpeg" required></div><div class="full" id="preview"></div></div><br><button>Submit Application</button></form></main>`;
document.getElementById('switch').onclick=()=>location.href=base+'admin';let f=document.getElementById('form'),role=f.specificRole;f.department.onchange=()=>{role.innerHTML='<option value="">Select Role</option>'+opt(branches[f.department.value]||[]);custom()};role.onchange=custom;function custom(){document.getElementById('customWrap').style.display=(role.value==='Other'||f.department.value==='Other')?'block':'none'}document.getElementById('file').onchange=async e=>{try{cv=await compress(e.target.files[0]);document.getElementById('preview').innerHTML=`<img class="thumb" src="${cv.data}"> <b>${esc(cv.name)}</b>`;setMsg('CV image compressed and ready.',true)}catch(er){cv=null;setMsg(er.message)}};f.onsubmit=async e=>{e.preventDefault();try{if(!cv)throw Error('Please upload CV image.');let data=Object.fromEntries(new FormData(f).entries());await addDoc(collection(db,'applications'),{...data,cvImageData:cv.data,cvImageName:cv.name,cvImageType:cv.type,cvImageSize:cv.size,applicationStatus:'New',hrRemarks:'',submittedAt:serverTimestamp(),updatedAt:serverTimestamp()});f.reset();role.innerHTML='<option value="">Select Role</option>';document.getElementById('preview').innerHTML='';cv=null;setMsg('Application submitted successfully. HR team will review it.',true)}catch(er){setMsg(er.message||'Submission failed.')}}}
function login(){root.innerHTML=`<main class="wrap">${header(true)}<form class="card" id="login"><h2>Admin Login</h2><div id="msg" hidden></div><div class="grid"><div><label>Email</label><input name="email" type="email" required></div><div><label>Password</label><input name="password" type="password" required></div></div><br><button>Login</button></form></main>`;document.getElementById('switch').onclick=()=>location.href=base;document.getElementById('login').onsubmit=async e=>{e.preventDefault();let f=e.target;try{await signInWithEmailAndPassword(auth,f.email.value,f.password.value)}catch(er){setMsg(er.message)}}}
async function load(){let snap=await getDocs(query(collection(db,'applications'),orderBy('submittedAt','desc')));rows=snap.docs.map(d=>({id:d.id,...d.data()}));dash()}
function dash(){let q=(document.getElementById('q')?.value||'').toLowerCase(),sd=document.getElementById('sd')?.value||'',ss=document.getElementById('ss')?.value||'';let list=rows.filter(r=>[r.name,r.phone,r.department,r.specificRole,r.customRole].join(' ').toLowerCase().includes(q)&&(!sd||r.department===sd)&&(!ss||r.applicationStatus===ss));root.innerHTML=`<main class="wrap">${header(true)}<section class="card"><div class="topbar"><h2>Applications (${list.length})</h2><div class="actions"><button id="csv">Export CSV</button><button class="danger" id="out">Logout</button></div></div><div class="filters"><input id="q" placeholder="Search name/phone/role" value="${esc(q)}"><select id="sd"><option value="">All Departments</option>${opt(Object.keys(branches))}</select><select id="ss"><option value="">All Status</option>${opt(statuses)}</select><button id="refresh">Refresh</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Date</th><th>Candidate</th><th>Dept / Role</th><th>CV</th><th>Status</th><th>Remarks</th><th>Save</th></tr></thead><tbody>${list.map(r=>`<tr><td>${date(r.submittedAt)}</td><td><b>${esc(r.name)}</b><br>${esc(r.phone)}</td><td>${esc(r.department)}<br><b>${esc(r.specificRole==='Other'?r.customRole:r.specificRole)}</b><br>${esc(r.workExperience)}</td><td>${r.cvImageData?`<img class="thumb" data-view="${r.id}" src="${r.cvImageData}"><br><button class="secondary" data-view="${r.id}">View</button>`:''}</td><td><select data-st="${r.id}">${statuses.map(s=>`<option ${s===(r.applicationStatus||'New')?'selected':''}>${s}</option>`).join('')}</select></td><td><textarea data-rm="${r.id}">${esc(r.hrRemarks||'')}</textarea></td><td><button data-save="${r.id}">Save</button></td></tr>`).join('')}</tbody></table></div></section></main>`;document.getElementById('switch').onclick=()=>location.href=base;document.getElementById('q').oninput=dash;document.getElementById('sd').value=sd;document.getElementById('ss').value=ss;document.getElementById('sd').onchange=dash;document.getElementById('ss').onchange=dash;document.getElementById('refresh').onclick=load;document.getElementById('out').onclick=()=>signOut(auth);document.getElementById('csv').onclick=()=>csv(list);document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{let id=b.dataset.save;await updateDoc(doc(db,'applications',id),{applicationStatus:document.querySelector(`[data-st="${id}"]`).value,hrRemarks:document.querySelector(`[data-rm="${id}"]`).value,updatedAt:serverTimestamp()});await load()});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(rows.find(x=>x.id===b.dataset.view)))}
function show(r){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modalbox"><div class="topbar"><h2>${esc(r.name)} - CV</h2><button class="secondary">Close</button></div><img src="${r.cvImageData}"><br><br><a download="${esc(r.cvImageName||'cv.jpg')}" href="${r.cvImageData}"><button>Download CV Image</button></a></div>`;m.onclick=e=>{if(e.target===m||e.target.tagName==='BUTTON')m.remove()};document.body.appendChild(m)}
function csv(list){let cols=['name','phone','department','specificRole','customRole','workExperience','applicationStatus','hrRemarks','submittedAt'];let s=[cols.join(','),...list.map(r=>cols.map(c=>'"'+String(c==='submittedAt'?date(r[c]):r[c]??'').replaceAll('"','""')+'"').join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='applications.csv';a.click();URL.revokeObjectURL(a.href)}
if(location.pathname.toLowerCase().includes('/admin'))onAuthStateChanged(auth,u=>{user=u;u?load():login()});else candidate();
